[project]
name = "dlip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.0",
    "tensorflow>=2.18.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
